    dockitems_to_remove:
      - Launchpad
      - Mail
      - Safari
      - Contacts
      - Notes
      - Reminders
      - Maps
      - Photos
      - Messages
      - FaceTime
      - iTunes
      - iBooks
      - App Store
      - System Preferences
      - Calendar
      - Siri
    
    dockitems_to_persist:
      - name: Google Chrome
        path: "/Applications/Google Chrome.app"
        pos: 1
      - name: Firefox
        path: "/Applications/Firefox.app"
        pos: 2
      - name: Visual Studio Code
        path: /Applications/Visual Studio Code.app
        pos: 3
      - name: Slack
        path: /Applications/Slack.app
        pos: 4
      - name: iTerm
        path: /Applications/iTerm.app
        pos: 5
      - name: Spotify
        path: /Applications/Spotify.app
        pos: 6