---

- hosts: localhost
  connection: local
  tasks:
    - name: install homebrew
      shell: '/usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"'
      register: gethomebrew_result
      changed_when: "'up-to-date' not in gethomebrew_result.stdout"

    - name: setup homebrew cask
      homebrew_tap:
        name: homebrew/cask
        state: present

    - name: brew cask apps ftw
      homebrew_cask:
        name: "{{ item }}"
        state: latest
      loop:
        - google-chrome
        - spotify
        - iterm2
        - firefox
        - slack
        - visual-studio-code
        - lastpass
    
    - name: homebrew apps ftw!
      homebrew:
        name: "{{ item }}"
        state: latest
      loop:
        - go
        - httpie
        - git
        - zsh
    
    - name: disable natural scroll
      osx_defaults:
        key: com.apple.swipescrolldirection
        type: bool
        value: "{{ natural_scroll | default(false) }}"

    - name: finder set enable
      osx_defaults:
        domain: com.apple.finder
        key: "{{ item }}"
        type: bool
        value: true
      with_items:
        - ShowStatusBar
        - ShowPathbar
        - ShowTabView
        - AppleShowAllFiles
        - _FXShowPosixPathInTitle
        - QLEnableTextSelection

    - name: disable siri
      osx_defaults:
        domain: "{{ item.domain }}"
        key: "{{ item.key }}"
        type: bool
        value: "{{ item.value }}"
      loop:
        - { domain: "com.apple.Siri", key: "Disabled", value: true }
        - { domain: "com.apple.Siri", key: "UserHasDeclinedEnable", value: true }
        - { domain: "com.apple.Siri", key: "StatusMenuVisible", value: false }
        - { domain: "com.apple.assistant.support", key: "Assistant Enabled", value: false }

    - name: set defaults for Control Strip (will always overwrite current config as of now..)
      shell: cat files/controlstrip.plist | defaults import - ~/Library/Preferences/com.apple.controlstrip.plist && killall ControlStrip
      
    - name: 'get "oh my zsh"'
      shell: sh -c "$(curl -fsSL https://raw.github.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"
      register: getohmyzsh_result
      changed_when: "'You already have Oh My Zsh installed' not in getohmyzsh_result.stdout"