---
    - name: Go path dirs
      file: 
        path: "{{ ansible_user_dir }}/go/{{ item }}"
        state: directory
      loop:
        - src
        - pkg
        - bin
      tags:
        - golang

    - name: Install golang packages
      command: "go get -u -v {{ item }}"
      loop: "{{ golang_default_packages }}"
      ignore_errors: yes
      tags:
        - golang