    golang_default_packages:
      - golang.org/x/tools/cmd/goimports
      - golang.org/x/tools/cmd/cover
      - golang.org/x/tools/cmd/godoc
      - golang.org/x/tools/go/packages
      - golang.org/x/lint/golint
      - github.com/golang/dep/cmd/dep
      - github.com/tools/godep
      - github.com/mitchellh/gox
      - github.com/spf13/viper
      - github.com/spf13/cobra