---
    - name: create .config-directory
      file:
        path: "{{ ansible_user_dir }}/.config/iterm2"
        state: directory
        
    - name: get the iterm2 fonts and color themes
      get_url: 
        url: "{{ item.url }}"
        dest: "{{ item.dest }}"
      loop:
        - {url: "https://raw.githubusercontent.com/powerline/fonts/master/SourceCodePro/Source%20Code%20Pro%20for%20Powerline.otf", dest: "~/Library/Fonts/Source Code Pro for Powerline.ttf"}
        - {url: "https://raw.githubusercontent.com/powerline/fonts/master/Meslo%20Slashed/Meslo%20LG%20M%20Regular%20for%20Powerline.ttf", dest: "~/Library/Fonts/Meslo LG M Regular for Powerline.ttf"}
        - {url: "https://raw.githubusercontent.com/altercation/solarized/master/iterm2-colors-solarized/Solarized%20Dark.itermcolors", dest: "{{ ansible_user_dir }}/.config/iterm2/Solarized Dark.itermcolors"}
        - {url: "https://raw.githubusercontent.com/altercation/solarized/master/iterm2-colors-solarized/Solarized%20Light.itermcolors", dest: "{{ ansible_user_dir }}/.config/iterm2/Solarized Light.itermcolors"}

    - name: set iTerm2 to load config from files
      osx_defaults:
        domain: com.googlecode.iterm2
        key: LoadPrefsFromCustomFolder
        type: bool
        value: true

    - name: set the folder for iTerm2 to load config from
      osx_defaults:
        domain: com.googlecode.iterm2
        key: PrefsCustomFolder
        type: string
        value: "{{ ansible_user_dir }}/.config/iterm2"        

    - name: template out iTerm2 config
      template:
        src: templates/com.googlecode.iterm2.plist.j2
        dest: "{{ ansible_user_dir }}/.config/iterm2/com.googlecode.iterm2.plist"
